# This file was generated by GoReleaser. DO NOT EDIT.
cask "fsend" do
  version "1.14.1"

  on_macos do
    on_arm do
      sha256 "c3f7d67691516b595d3a5d9b68d2700e07ae5913a682f28c0b14fa89ad03c8ae"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "537fa3d526b82796436b734122285a40e09b9cb26dc16b97b5ef38fabaeef6f5"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d772083b7962a7c41baaf5f00772adbb77ebd6c131c3870c642134d1e8b80c8"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e3c3b4b74df41e0b347c4dac7a37723853bb4a0c5c676572d076b715cfc7904"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fsend"
  desc "Peer-to-peer, end-to-end encrypted file transfer"
  homepage "https://github.com/polius/fsend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fsend"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fsend"]
    end
  end

  # No zap stanza required
end
