# This file was generated by GoReleaser. DO NOT EDIT.
cask "fsend" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "2d43e9c24e33b9af3588b78918fb3bef853b01ab836541882eb3a1981a5d4e80"
      url "https://github.com/polius/fsend/releases/download/v1.9.0/fsend_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dce132052347ca9cb865cd4df068c74a9c7ee55af8b08c94ad97da6ef12d7255"
      url "https://github.com/polius/fsend/releases/download/v1.9.0/fsend_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70f9a3548728be50d7b7a2ce5cae51f1a184ae6dff768cb7eff9876bdfeb30bb"
      url "https://github.com/polius/fsend/releases/download/v1.9.0/fsend_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "840bdb2635dc36acd4c39b98b6013f5b1bceb32fb745e11b03bfc21dae14fc84"
      url "https://github.com/polius/fsend/releases/download/v1.9.0/fsend_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fsend"
  desc "Peer-to-peer, end-to-end encrypted file transfer"
  homepage "https://github.com/polius/fsend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fsend"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fsend"]
    end
  end

  # No zap stanza required

end
