# This file was generated by GoReleaser. DO NOT EDIT.
cask "fsend" do
  version "1.12.0"

  on_macos do
    on_arm do
      sha256 "b2a602667ee155d1daa04d462772832cda0eb0ee7ef64851f4003c921e6cee6f"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c48399a4f9e2a63ef0a13b1bd949039822080b4816cdd8b3ddc2b01f99faa6a3"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "48ce190d354eef1230b1b1bf58d199d1fad2aa637afe250d48a0667a2b5d2347"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d6a7b28844bd0b4fe64e0213a7db8e2b0b2a4366b50bc7f7799486d07c9f55b"
      url "https://github.com/polius/fsend/releases/download/v#{version}/fsend_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fsend"
  desc "Peer-to-peer, end-to-end encrypted file transfer"
  homepage "https://github.com/polius/fsend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fsend"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fsend"]
    end
  end

  # No zap stanza required
end
